import { build, version as esbuildVersion } from 'esbuild';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { gzipSync } from 'node:zlib';

const project = fileURLToPath(new URL('../', import.meta.url));
const posix = value => value.split(path.sep).join('/');
const targets = ['es2022', 'safari16'];

// Sources remain readable in dist. Only this entry bundle is needed at runtime;
// asset URLs stay document-relative so a GitHub Pages repository prefix works.
export async function createWebBuild({ root = project } = {}) {
  root = path.resolve(root);
  const result = await build({
    absWorkingDir: root,
    entryPoints: ['dist/explore.js'],
    outfile: 'dist/app.bundle.js',
    alias: { three: './dist/vendor/three.module.js' },
    bundle: true,
    minify: true,
    platform: 'browser',
    format: 'esm',
    target: targets,
    charset: 'utf8',
    legalComments: 'linked',
    metafile: true,
    write: false,
    logLevel: 'silent',
    banner: { js: '/* Generated by scripts/build-web.mjs. Licenses: ./LICENSE-SCOPE.md and ./app.bundle.js.LEGAL.txt */' }
  });
  const bundles = Object.entries(result.metafile.outputs).filter(([name]) => name.endsWith('.js'));
  if (bundles.length !== 1 || posix(bundles[0][0]) !== 'dist/app.bundle.js' || bundles[0][1].imports.length) {
    throw new Error('Expected one self-contained JavaScript bundle without external module requests.');
  }
  const inputNames = Object.keys(result.metafile.inputs);
  if (inputNames.some(name => !posix(name).startsWith('dist/'))) {
    throw new Error('Browser bundle must use vendored sources under dist, not installed runtime packages.');
  }
  const outputFiles = new Map(result.outputFiles.map(file => [posix(path.relative(root, file.path)), Buffer.from(file.contents)]));
  if (!outputFiles.has('dist/app.bundle.js.LEGAL.txt')) throw new Error('Missing extracted legal notices.');

  const css = await readFile(path.join(root, 'dist/explore.css'), 'utf8');
  if (/<\/style\b/i.test(css)) throw new Error('Stylesheet contains an unsafe closing style tag.');
  for (const name of ['dist/index.html', 'dist/explore.html']) {
    const html = await readFile(path.join(root, name), 'utf8');
    const marker = /(<style\s+id=["']app-style["']\s*>)[\s\S]*?<\/style>/gi;
    const matches = [...html.matchAll(marker)];
    if (matches.length !== 1) throw new Error(`${name} requires exactly one <style id="app-style"> marker.`);
    outputFiles.set(name, Buffer.from(html.replace(marker, (_match, opening) => `${opening}\n${css.trim()}\n</style>`)));
  }

  const inputBuffers = await Promise.all(inputNames.map(name => readFile(path.resolve(root, name))));
  const bundle = outputFiles.get('dist/app.bundle.js');
  const stats = {
    esbuild: esbuildVersion,
    targets,
    sourceModules: inputNames.length,
    retainedModules: Object.keys(bundles[0][1].inputs).length,
    runtimeJavaScriptFiles: bundles.length,
    sourceBytes: inputBuffers.reduce((sum, bytes) => sum + bytes.length, 0),
    sourceGzipBytes: inputBuffers.reduce((sum, bytes) => sum + gzipSync(bytes, { level: 9 }).length, 0),
    bundleBytes: bundle.length,
    bundleGzipBytes: gzipSync(bundle, { level: 9 }).length,
    legalBytes: outputFiles.get('dist/app.bundle.js.LEGAL.txt').length,
    inlineCssBytes: Buffer.byteLength(css.trim())
  };
  return { root, outputFiles, stats, metafile: result.metafile };
}

// --check builds in memory and compares every generated byte. It cannot silently
// regenerate a stale artifact in CI or contaminate the clean release checkout.
export async function applyWebBuild(result, { check = false } = {}) {
  const stale = [];
  for (const [name, contents] of result.outputFiles) {
    const destination = path.join(result.root, name);
    if (check) {
      let current;
      try { current = await readFile(destination); }
      catch (error) { if (error.code !== 'ENOENT') throw error; }
      if (!current?.equals(contents)) stale.push(name);
    } else {
      await writeFile(destination, contents);
    }
  }
  if (stale.length) throw new Error(`Generated website is stale or missing: ${stale.join(', ')}. Run npm run build and commit the updated artifacts.`);
}

async function main() {
  const args = process.argv.slice(2);
  let check = false, report;
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--check') check = true;
    else if (args[i] === '--report' && args[i + 1]) report = path.resolve(args[++i]);
    else throw new Error('Usage: node scripts/build-web.mjs [--check] [--report work/web-build.json]');
  }
  const result = await createWebBuild();
  await applyWebBuild(result, { check });
  const s = result.stats;
  console.log(`${check ? 'PASS: committed website matches source' : 'Built website'} with esbuild ${s.esbuild}.`);
  console.log(`JavaScript: ${s.sourceModules} source modules -> ${s.runtimeJavaScriptFiles} bundle; ${s.sourceBytes} -> ${s.bundleBytes} bytes (${(100 * (1 - s.bundleBytes / s.sourceBytes)).toFixed(1)}% smaller).`);
  console.log(`Gzip estimate: ${s.sourceGzipBytes} bytes across source files -> ${s.bundleGzipBytes} bytes; legal notices ${s.legalBytes} bytes; inline CSS ${s.inlineCssBytes} bytes.`);
  if (report) {
    await mkdir(path.dirname(report), { recursive: true });
    await writeFile(report, JSON.stringify({ stats: s, metafile: result.metafile }, null, 2) + '\n');
    console.log(`Build report: ${report}`);
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch(error => { console.error(`Web build failed: ${error.message}`); process.exitCode = 1; });
}
